#!/usr/bin/env ruby

require_relative "./yield_function"

class Region
  def initialize
    @gatherer_func = YieldFunction.new(20, 3.0, 40, 1.0)
  end

  def food(tribe)
    @gatherer_func.call(tribe.work)
  end
end

class Tribe
  attr_accessor :food

  def initialize(ages)
    @ages = ages.dup
  end

  def work
    @ages.count{|age| age >= 15}
  end

  def food_need
    @ages.size * 2.0
  end

  def food_sat
    (food / food_need).round(3)
  end

  def simulate
    sat = food_sat
    # Everyone gets one year older
    @ages.size.times{|i| @ages[i] += 1}
    # Everyone is bigender for now
    # Ignore old man - young woman pairs
    fertile_women = (@ages.count{|age| (15..40).include?(age) } / 2)
    # 20% below sat people just stop having babies
    if sat >= 0.8
      # fertile women pregnant 50% of time
      # hmm, why 4 minimum to even reproduce?
      @ages += [0] * (0...fertile_women).count{ rand < 0.5 }
    end
    # Now kill 2% of people
    @ages = @ages.select{|a| rand < 0.98}
  end

  def count_elderly
    @ages.count{|age| age > 40 }
  end

  def count_adult
    @ages.count{|age| (15..40).include?(age) }
  end

  def could_children
    @ages.count{|age| age < 15}
  end

  def report
    # puts "#{self.class}<#{@ages}> #{food}/#{food_need}"
    puts "#{self.class}<#{count_elderly}/#{count_adult}/#{could_children}> #{food}/#{food_need} (#{(100*food_sat).round}%)"
  end
end

region = Region.new
# two pairs just in case someone dies too early
tribe = Tribe.new([15,15,15,15])

1000.times do
  tribe.food = region.food(tribe)
  tribe.report
  tribe.simulate
end
