#!/usr/bin/env ruby

require "set"

class Tribe
  attr_accessor :name, :energy, :biome, :techs

  def initialize(name, biome)
    @name = name
    @energy = 10.0
    @biome = biome
    @techs = Set[]
  end

  def call
    return if dead?
    @energy += 1.0 + rand * 5.0
    @energy -= biome.cost
    if @energy >= 10.0
      @energy = 10.0
    end
  end

  def dead?
    @energy < 0.0
  end

  def report
    if dead?
      puts "#{@name} in #{@biome.name} - DEAD"
    else
      puts "#{@name} in #{@biome.name} - #{@energy.round(2)}"
    end
  end
end

class Biome
  attr_reader :name, :cost

  def initialize(name, cost)
    @name = name
    @cost = cost
  end
end

r1 = Biome.new("Forest", 3.0)
r2 = Biome.new("Dessert", 5.0)
r3 = Biome.new("Rainforest", 2.0)
t1 = Tribe.new("Tribe 1", r1)
t2 = Tribe.new("Tribe 2", r2)
t3 = Tribe.new("Tribe 3", r3)
tribes = [t1, t2, t3]

20.times do |i|
  puts "Time #{i}"
  tribes.each(&:call)
  tribes.each(&:report)
end
