#!/usr/bin/env ruby

require "set"

class Tribe
  attr_accessor :name, :energy, :biome, :techs

  def initialize(name, biome)
    @name = name
    @energy = 10.0
    @biome = biome
    @techs = Set[]
  end

  def call
    return if dead?
    @energy += 1.0 + rand * 5.0
    @energy -= biome.cost
    if @energy >= 10.0
      @energy = 10.0
    end
  end

  def dead?
    @energy < 0.0
  end

  def report
    if dead?
      puts "#{@name} in #{@biome.name} - DEAD"
    else
      puts "#{@name} in #{@biome.name} - #{@energy.round(2)}"
    end
  end
end

class Biome
  attr_reader :name, :cost

  def initialize(name, cost)
    @name = name
    @cost = cost
  end
end

class Simulation
  def initialize
    @biomes = [
      Biome.new("Forest", 3.0),
      Biome.new("Desert", 5.0),
      Biome.new("Rainforest", 2.0),
    ]
    @tribe_counter = 0
    @tribes = []
  end

  def random_tribe
    @tribe_counter += 1
    Tribe.new("Tribe #{@tribe_counter}", @biomes.sample)
  end

  def call
    10.times do
      @tribes << random_tribe
    end

    20.times do |i|
      puts "Time #{i}"
      @tribes.each(&:call)
      @tribes.each(&:report)
      @tribes.delete_if(&:dead?)
      @tribes << random_tribe while @tribes.size < 10
    end
  end
end

Simulation.new.call
